
const conditions = [
	"is the oldest",
	"is the second-oldest",
	"is the youngest",
	"is the second-youngest",
	"is the tallest",
	"is the second-tallest",
	"is the shortest",
	"is the second-shortest",
	"is carrying the most keys",
	"is carrying the fewest keys",
	"is wearing the newest item of clothing",
	"has the alphabetically first first name",
	"has the alphabetically last first name",
	"has the alphabetically first last name",
	"has the alphabetically last last name",
	"lives on the alphabetically first street",
	"lives on the alphabetically last street",
	"was born in the alphabetically first province or state",
	"was born in the alphabetically last province or state",
	"has the longest first name",
	"has the shortest first name",
	"has the longest last name",
	"has the shortest last name",
	"has the most siblings",
	"has the fewest siblings",
	"has visited the most nations outside Canada",
	"has visited the fewest nations outside Canada",
	"has travelled the furthest north",
	"has travelled the furthest south",
	"lives at the lowest street number",
	"lives at the highest street number",
	"has the lowest last digit in their Social Insurance Number",
	"has the highest last digit in their Social Insurance Number",
	"has the second-highest last digit in their Social Insurance Number",
	"has the highest (age % 7)",
	"has the lowest (age % 7)",
	"had the most recent birthday",
	"will have the next birthday",
	"most recently ate a donut",
	"most recently ate an apple",
	"most recently ate fish",
	"most recently ate kale",
	"most recently ate an orange",
	"most recently ate a banana",
	"most recently ate a carrot",
	"most recently ate pie",
	"most recently ate ice cream",
	"most recently ate fries",
	"most recently ate yoghurt",
	"most recently ate toast",
	"most recently ate cheese",
	"most recently ate pancakes",
	"most recently ate strawberries",
	"most recently ate avocado",
	"most recently ate chocolate",
	"most recently ate tofu",
	"most recently drank water",
	"most recently drank milk",
	"most recently rode a bus",
	"most recently rode a bicycle",
	"most recently rode in an elevator",
	"most recently paddled a canoe or kayak",
	"most recently slept in a tent",
	"most recently walked or ran more than 1 km",
	"most recently climbed a ladder",
	"most recently climbed a tree",
	"most recently went up or down a flight of stairs",
	"most recently crossed a bridge",
	"most recently visited Toronto",
	"most recently visited Ottawa",
	"most recently visited Montreal",
	"most recently visited the USA",
	"most recently visited a farm",
	"most recently visited a zoo",
	"most recently was on a beach",
	"most recently bought flowers",
	"most recently bought music",
	"most recently bought shoes",
	"most recently bought eggs",
	"most recently bought a hot drink",
	"most recently visited a dentist",
	"least recently visited a dentist",
	"most recently travelled by train",
	"least recently travelled by train",
	"most recently travelled by plane",
	"least recently travelled by plane",
	"most recently rode a horse or camel",
	"least recently rode a horse or camel",
	"most recently swam in a lake or river",
	"least recently swam in a lake or river",
	"most recently watered a plant",
	"least recently watered a plant",
	"most recently took a photograph",
	"least recently took a photograph",
	"most recently made tea",
	"least recently made tea",
	"most recently made coffee",
	"least recently made coffee",
	"most recently watched anything on Netflix",
	"least recently watched anything on Netflix",
	"most recently used FACEBOOK",
	"least recently used FACEBOOK",
	"most recently sneezed",
	"most recently watched a movie in a theatre",
	"most recently replaced their phone",
	"has had their current phone the longest",
	"most recently baked something"
  ]  


const quotes = [
	"A sword-day, a red day!",
	"Ach du lieber!",
	"Are you insane?",
	"Awwwww HELL No!",
	"Ay De Mi!",
	"Bah!  Humbug!",
	"Begorrah!",
	"Bejabbers!",
	"Bless my spillikeens!",
	"Blistering blue barnacles!",
	"Blood and thunder!",
	"By the Hammer of Thor!",
	"Che fregatura!!",
	"Chiminelas Caranchita!",
	"Cry 'Havoc!'",
	"Dadgum it!",
	"DAMMIT!!",
	"Facinore horribilis!",
	"Gadsbudlikins!",
	"Gadzooks!",
	"Get OUT of here!",
	"Give me a break!",
	"Great Caesar's Ghost!",
	"Great googly moogly!",
	"Great horn spoon!",
	"Holy pretzel!",
	"How quaint.",
	"I demand justice!",
	"I want a do-over.",
	"I ... Can't ... Even.",
	"Is this a joke?",
	"Is this fake news?",
	"It's a conspiracy!",
	"It's an outrage!",
	"It's never me!",
	"Lame as a very lame thing",
	"Mamma Mia!",
	"Mere anarchy.",
	"My kingdom for a horse!",
	"Never saw THAT coming.",
	"Nooooooooooooooooooo!",
	"No no no no no no no",
	"Not this again.",
	"Not me.  As usual.",
	"Odin's Raven!",
	"Oh come ON!",
	"Oh fishhooks!",
	"Oh my wig and whiskers!",
	"Oh sweet cheese and crackers!",
	"OMG! Are you kidding me?",
	"Please, not that!",
	"Potzblitz!",
	"Release the Kraken!",
	"Seriously?",
	"Shih Tzu and Dalmation!",
	"Shut! Up!",
	"Spank me with a wet fish!",
	"Spock!  Explain!",
	"So ein Misthaufen!",
	"That's evil.",
	"That's just silly.",
	"The system is rigged!",
	"Think you're smart, eh?",
	"This is cruel and unusual.",
	"This is just revolting!",
	"This totally sucks!",
	"Thundering typhoons!",
	"Typical.  Juuuuuust typical.",
	"Unfair!!",
	"Well call me a biscuit!",
	"Well I'll be jitterbugged",
	"Well lick my knees!",
	"Well pickle my trotters!",
	"What is WRONG with you?",
	"What the actual heck?",
	"What?",
	"Who came up with this?",
	"Whose dumb idea was that?",
	"You monsters!",
	"You won't get away with this!",
	"Your honour, I object.",
	"You'll pay for this!",
	"You'll regret this.",
	"Yumping Yiminy!",
	"Zoinks!",
];

function refresh() {
	const face = document.querySelector("#face");
	face.src=`images/faces/face-${Math.floor(Math.random()*61)+1}.jpg`;

	const winner = document.querySelector("#condition");
	winner.textContent=conditions[Math.floor(Math.random()*conditions.length)];
	
	const quote = document.querySelector("#quote");
	quote.textContent=quotes[Math.floor(Math.random()*quotes.length)];
}
window.addEventListener("load", function() {
	refresh();
	document.body.addEventListener("click", ()=> {
		refresh();
	});
});
